controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
register:
    path: /api/register
    controller: App\Controller\AuthController::register
login:
    path: /api/login
contact:
    path: /api/contact
    controller: App\Controller\StoreContactController::index
