controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
test:
    path: /test
    controller: App\Controller\TestController
auth:
    path: /register
    controller: App\Controller\AuthController::register
